# Generated by Django 4.2.1 on 2023-07-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_name', models.CharField(max_length=35)),
                ('cliente_apellido', models.CharField(max_length=35)),
                ('cliente_telefono', models.CharField(max_length=35)),
                ('cliente_correo', models.CharField(max_length=35)),
                ('cliente_cedula', models.CharField(max_length=15)),
                ('cliente_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_id', models.CharField(max_length=25)),
                ('product_price', models.IntegerField()),
                ('product_lot', models.IntegerField()),
            ],
        ),
    ]
