# Generated by Django 4.2.1 on 2023-07-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_name', models.CharField(max_length=35)),
                ('cliente_apellido', models.CharField(max_length=35)),
                ('cliente_telefono', models.CharField(max_length=35)),
                ('cliente_correo', models.CharField(max_length=35)),
                ('cliente_cedula', models.CharField(max_length=15)),
                ('cliente_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price_ref', models.FloatField()),
                ('available', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('lote', models.IntegerField()),
            ],
        ),
    ]
