# Generated by Django 4.2.2 on 2023-07-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_remove_product_price_product_price_bs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_bs',
        ),
    ]
