# Generated by Django 4.2.2 on 2023-07-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0003_remove_product_price_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
