# Generated by Django 4.2.2 on 2023-07-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0004_product_available_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('cedula', models.IntegerField()),
                ('phone_number', models.FloatField()),
                ('email', models.CharField(max_length=25)),
            ],
        ),
    ]
