# Generated by Django 4.2.2 on 2023-07-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0005_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
